# Generated by Django 4.2.2 on 2023-11-19 12:08

from django.db import migrations
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.managers.CustomUserManager()),
                ('specialists', main.managers.SpecialistsManager()),
            ],
        ),
    ]
