# Generated by Django 4.2.2 on 2023-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='активирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False, verbose_name='Массажист'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates hello whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='активен'),
        ),
    ]
