# Generated by Django 4.2.2 on 2023-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False, verbose_name='Массажист'),
        ),
    ]
