# Generated by Django 4.2.2 on 2023-09-04 19:00

from django.db import migrations
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_activated_user_is_therapist_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.managers.CustomUserManager()),
            ],
        ),
    ]
