# Generated by Django 4.2.2 on 2023-09-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_alter_avatar_image_alter_gallery_date_added'),
        ('main', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.avatar'),
        ),
    ]
