version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: ./tantrakazan/Dockerfile
    container_name: web-app-testdjango
    command: poetry run python tantrakazan/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/home/app
    ports:
      - "8000:8000"
    env_file:
      - ./tantrakazan/.env