version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: ./tantrakazan/Dockerfile
    container_name: web-app-testdjango
    command: ./tantrakazan/entrypoint.sh
    volumes:
      - ./tantrakazan:/home/tantrakazan
    ports:
      - "8000:8000"
    env_file:
      - tantrakazan/.env.dev