# Generated by Django 4.2.2 on 2023-09-05 18:34

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='название')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='слаг')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст статьи')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 9, 5, 21, 34, 35, 1341), verbose_name='дата создания')),
                ('last_update', models.DateTimeField(default=datetime.datetime(2023, 9, 5, 21, 34, 35, 1358), verbose_name='дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-last_update', '-pk'],
                'get_latest_by': 'last_update',
                'unique_together': {('author', 'title'), ('author', 'slug')},
            },
        ),
    ]
