# Generated by Django 5.0 on 2023-12-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('star_ratings', '0004_alter_rating_id_alter_userrating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Отзыв')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatingAdminModel',
            fields=[
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('star_ratings.userrating',),
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('bookmark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.bookmark')),
                ('like_or_dislike', models.BooleanField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], default=True, verbose_name='голос')),
            ],
            bases=('feedback.bookmark',),
        ),
    ]
