# Generated by Django 4.2.2 on 2023-08-30 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_comment_date_added_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='like_or_dislike',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 21, 15, 12, 442489), verbose_name='дата создания'),
        ),
    ]
