# Generated by Django 4.2.2 on 2023-09-02 13:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0005_favorite_like_or_dislike_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 16, 22, 1, 785803), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='like_or_dislike',
            field=models.BooleanField(choices=[(True, 'Like'), (False, 'Dislike')], default=True, verbose_name='лайк или дизлайк'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('author', 'content_type', 'object_id')},
        ),
    ]
