# Generated by Django 4.2.2 on 2023-09-05 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 21, 36, 19, 937595), verbose_name='дата создания'),
        ),
    ]
