# Generated by Django 4.2.2 on 2023-09-06 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 21, 39, 34, 465575), verbose_name='дата создания'),
        ),
    ]
