# Generated by Django 4.2.2 on 2023-09-11 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 21, 21, 56, 195011), verbose_name='дата создания'),
        ),
    ]
