# Generated by Django 4.2.2 on 2023-09-17 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 21, 29, 7, 667445), verbose_name='дата создания'),
        ),
    ]
