# Generated by Django 4.2.2 on 2023-09-21 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 32, 5, 590008), verbose_name='дата создания'),
        ),
    ]
