# Generated by Django 4.2.2 on 2023-09-30 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 11, 37, 36, 120965), verbose_name='дата создания'),
        ),
    ]
