# Generated by Django 4.2.2 on 2023-09-30 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0023_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 12, 30, 1, 442439), verbose_name='дата создания'),
        ),
    ]
