# Generated by Django 4.2.2 on 2023-09-30 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 15, 56, 6, 557609), verbose_name='дата создания'),
        ),
    ]
