# Generated by Django 4.2.2 on 2023-10-20 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0027_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 21, 44, 37, 627362), verbose_name='дата создания'),
        ),
    ]
