# Generated by Django 4.2.2 on 2023-10-20 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0029_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 22, 20, 21, 334737), verbose_name='дата создания'),
        ),
    ]
