# Generated by Django 4.2.2 on 2023-10-26 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0043_review_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.AddField(
            model_name='review',
            name='review_for',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for', related_query_name='review_for', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв на'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 21, 12, 18, 367000), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comment', related_query_name='child_comments', to='feedback.review', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(blank=True, verbose_name='Оценка'),
        ),
    ]
