# Generated by Django 4.2.2 on 2023-10-26 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0044_remove_review_object_id_review_review_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 21, 18, 48, 719047), verbose_name='Дата создания'),
        ),
    ]
