# Generated by Django 4.2.2 on 2023-10-26 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0045_remove_review_content_type_alter_review_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 21, 51, 19, 324827), verbose_name='Дата создания'),
        ),
    ]
