# Generated by Django 4.2.2 on 2023-10-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0004_alter_rating_id_alter_userrating_id'),
        ('feedback', '0047_review_average_review_content_type_review_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='star_ratings.userrating', verbose_name='Оценка'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='average',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='total',
        ),
    ]
