# Generated by Django 4.2.2 on 2023-10-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0004_alter_rating_id_alter_userrating_id'),
        ('feedback', '0048_alter_review_unique_together_review_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='star_ratings.userrating', verbose_name='Оценка'),
        ),
    ]
