# Generated by Django 5.0 on 2023-12-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicserviceprice',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialists.specialistprofile'),
        ),
    ]
