# Generated by Django 4.2.2 on 2023-08-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_tag_alter_listing_options_remove_listing_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
