# Generated by Django 4.2.2 on 2023-07-08 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_listing_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='therapist',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='listing', related_query_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Массажист'),
        ),
    ]
