# Generated by Django 4.2.2 on 2023-12-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='specialist',
            new_name='user',
        ),
    ]
