# Generated by Django 4.2.2 on 2023-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='duration',
            field=models.DurationField(verbose_name='продолжительность'),
        ),
    ]
