# Generated by Django 4.2.2 on 2023-10-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_is_active_remove_listing_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagefor',
            name='specialist',
        ),
    ]
