# Generated by Django 4.2.2 on 2023-10-20 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_therapistprofile_massage_to_couples'),
        ('listings', '0008_remove_massagefor_specialist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicServices',
            new_name='BasicService',
        ),
    ]
