# Generated by Django 4.2.2 on 2023-10-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_rename_basicservices_basicservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='specialist',
        ),
    ]
