# Generated by Django 4.2.2 on 2023-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_feature_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagefor',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
