# Generated by Django 4.2.2 on 2023-10-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_massagefor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicservice',
            name='specialist',
        ),
    ]
