# Generated by Django 4.2.2 on 2023-10-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_basicservice_home_price_basicservice_on_site_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicservice',
            name='home_price',
        ),
        migrations.RemoveField(
            model_name='basicservice',
            name='on_site_price',
        ),
        migrations.RemoveField(
            model_name='basicservice',
            name='specialist',
        ),
        migrations.CreateModel(
            name='BasicServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_price', models.PositiveSmallIntegerField(null=True, verbose_name='Приём у себя')),
                ('on_site_price', models.PositiveSmallIntegerField(null=True, verbose_name='Выезд на дом')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.basicservice')),
            ],
        ),
    ]
