# Generated by Django 4.2.2 on 2023-10-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_therapistprofile_basic_services_and_more'),
        ('listings', '0016_remove_basicservice_home_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicserviceprice',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.therapistprofile'),
        ),
    ]
