# Generated by Django 4.2.2 on 2023-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_basicserviceprice_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagefor',
            name='icon',
            field=models.CharField(max_length=50, null=True, verbose_name='Иконка'),
        ),
    ]
