# Generated by Django 4.2.2 on 2023-11-02 17:57

import autoslug.fields
from django.db import migrations, models
import gallery.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=gallery.models.BaseImage.generate_slug, unique=True, verbose_name='слаг')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/avatars', verbose_name='Фото профиля')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=gallery.models.get_storage_path, verbose_name='фото')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=gallery.models.BaseImage.generate_slug, unique=True, verbose_name='слаг')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'фото',
                'ordering': ['-upload_date', '-pk'],
                'get_latest_by': 'upload_date',
            },
        ),
    ]
