# Generated by Django 4.2.2 on 2023-08-23 17:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 20, 8, 34, 382031), verbose_name='дата создания')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_public', models.BooleanField(default=True, help_text='Public galleries will be displayed in the default views.', verbose_name='отображать')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'ordering': ['-date_added', '-pk'],
                'get_latest_by': 'date_added',
                'unique_together': {('user', 'title'), ('user', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='слаг')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=gallery.models.get_storage_path, verbose_name='фото')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='photos', to='gallery.gallery', verbose_name='альбом')),
            ],
            options={
                'verbose_name': 'фото',
                'ordering': ['-created_at', '-pk'],
                'get_latest_by': 'created_at',
            },
            bases=(gallery.models.ThumbnailsMixin, models.Model),
        ),
    ]
