# Generated by Django 4.2.2 on 2023-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'upload_date', 'ordering': ['-is_avatar', '-upload_date', '-pk'], 'verbose_name': 'фото'},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_avatar',
            field=models.BooleanField(default=False, verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
