# Generated by Django 4.2.2 on 2023-08-01 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 15, 30, 9, 228348), verbose_name='дата создания'),
        ),
    ]
