# Generated by Django 4.2.2 on 2023-08-26 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 21, 53, 45, 156388), verbose_name='дата загрузки'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 21, 53, 45, 155838), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photos', to='gallery.gallery', verbose_name='альбом'),
        ),
    ]
