# Generated by Django 4.2.2 on 2023-08-27 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_upload_date_alter_gallery_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 9, 26, 2, 958593), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 9, 26, 2, 959176), verbose_name='дата загрузки'),
        ),
    ]
