# Generated by Django 4.2.2 on 2023-08-08 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_date_added_alter_gallery_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 17, 35, 9, 459147), verbose_name='дата создания'),
        ),
    ]
