# Generated by Django 4.2.2 on 2023-08-28 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_date_added_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 20, 26, 33, 357647), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 20, 26, 33, 358229), verbose_name='дата загрузки'),
        ),
    ]
