# Generated by Django 4.2.2 on 2023-08-28 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_gallery_date_added_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 21, 0, 52, 8056), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 21, 0, 52, 8775), verbose_name='дата загрузки'),
        ),
    ]
