# Generated by Django 4.2.2 on 2023-08-30 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_gallery_date_added_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 10, 4, 48, 884331), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 10, 4, 48, 884902), verbose_name='дата загрузки'),
        ),
    ]
