# Generated by Django 4.2.2 on 2023-08-09 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 22, 59, 14, 699566), verbose_name='дата создания'),
        ),
    ]
