# Generated by Django 4.2.2 on 2023-08-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 20, 46, 46, 516481), verbose_name='дата создания'),
        ),
    ]
