# Generated by Django 4.2.2 on 2023-09-02 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_alter_gallery_date_added_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 16, 22, 1, 815449), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 16, 22, 1, 816244), verbose_name='дата загрузки'),
        ),
    ]
