# Generated by Django 4.2.2 on 2023-09-04 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_gallery_date_added_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 22, 0, 30, 102024), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 22, 0, 30, 102591), verbose_name='дата загрузки'),
        ),
    ]
