# Generated by Django 4.2.2 on 2023-09-17 18:29

import autoslug.fields
import datetime
from django.db import migrations, models
import gallery.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_alter_gallery_date_added_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 21, 29, 7, 966987), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=gallery.models.get_storage_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=gallery.models.BaseImage.generate_slug, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='название'),
        ),
    ]
