# Generated by Django 4.2.2 on 2023-09-21 18:32

import autoslug.fields
import datetime
from django.db import migrations, models
import gallery.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_alter_gallery_date_added_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=gallery.models.BaseImage.generate_slug, unique=True, verbose_name='слаг')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=gallery.models.get_storage_path, verbose_name='фото')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 32, 5, 802347), verbose_name='дата создания'),
        ),
    ]
