# Generated by Django 4.2.2 on 2023-09-30 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_avatar_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatars', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 11, 37, 36, 271248), verbose_name='дата создания'),
        ),
    ]
