# Generated by Django 4.2.2 on 2023-10-20 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0038_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 21, 44, 37, 786299), verbose_name='дата создания'),
        ),
    ]
