# Generated by Django 4.2.2 on 2023-10-23 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0050_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 12, 43, 7, 50207), verbose_name='дата создания'),
        ),
    ]
