# Generated by Django 4.2.2 on 2023-10-25 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0051_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 21, 8, 45, 926443), verbose_name='дата создания'),
        ),
    ]
