# Generated by Django 4.2.2 on 2023-10-28 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0057_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 9, 15, 52, 928265), verbose_name='дата создания'),
        ),
    ]
