# Generated by Django 4.2.2 on 2023-10-28 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0058_alter_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 18, 3, 13, 949396), verbose_name='дата создания'),
        ),
    ]
