# Generated by Django 4.2.2 on 2023-07-31 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img/avatars', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(blank=True, choices=[(True, 'Мужчина'), (False, 'Женщина')], null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Возраст')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес')),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес')),
                ('show_address', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('show_phone_number', models.BooleanField(default=True)),
                ('telegram_profile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграмм')),
                ('show_telegram_profile', models.BooleanField(default=True)),
                ('instagram_profile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Инстаграм')),
                ('show_instagram_profile', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('is_profile_active', models.BooleanField(default=True)),
                ('services', models.ManyToManyField(blank=True, to='listings.service', verbose_name='Услуги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
