# Generated by Django 4.2.2 on 2023-11-02 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(blank=True, choices=[(True, 'Мужчина'), (False, 'Женщина')], null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Возраст')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес')),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('telegram_profile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграмм')),
                ('instagram_profile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Инстаграм')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('is_profile_active', models.BooleanField(default=True)),
                ('basic_services', models.ManyToManyField(blank=True, to='listings.basicservice')),
                ('features', models.ManyToManyField(blank=True, to='listings.feature')),
                ('massage_for', models.ManyToManyField(to='listings.massagefor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', related_query_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
