# Generated by Django 4.2.2 on 2023-06-27 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageTherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Фото профиля')),
                ('gender', models.BooleanField(verbose_name='Пол')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('address', models.CharField(max_length=40, verbose_name='Адрес')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('telegram_profile', models.CharField(max_length=20, verbose_name='Телеграмм')),
                ('description', models.TextField(verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('caption', models.CharField(max_length=255, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.massagetherapistprofile', verbose_name='Юзер')),
            ],
        ),
    ]
