# Generated by Django 4.2.2 on 2023-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала практики'),
        ),
    ]
