# Generated by Django 4.2.2 on 2023-06-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagetherapistprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='massagetherapistprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='massagetherapistprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='massagetherapistprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='massagetherapistprofile',
            name='weight',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Фото профиля')),
                ('gender', models.BooleanField(verbose_name='Пол')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
