# Generated by Django 4.2.2 on 2023-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userprofile_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
