# Generated by Django 4.2.2 on 2023-11-19 12:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        ('users', '0002_remove_therapistprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='massage_for',
            field=models.ManyToManyField(related_name='specialists', related_query_name='specialist', to='listings.massagefor'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[users.models.validate_age], verbose_name='Вес'),
        ),
    ]
