# Generated by Django 4.2.2 on 2023-07-04 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_massagetherapistprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagetherapistprofile',
            name='experience',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='massagetherapistprofile',
            name='address',
            field=models.CharField(max_length=40, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='massagetherapistprofile',
            name='contact_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='massagetherapistprofile',
            name='description',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='massagetherapistprofile',
            name='telegram_profile',
            field=models.CharField(max_length=20, null=True, verbose_name='Телеграмм'),
        ),
        migrations.AlterField(
            model_name='massagetherapistprofile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='massage_therapist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Мужчина'), (False, 'Женщина')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Вес'),
        ),
    ]
