# Generated by Django 4.2.2 on 2023-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_therapistprofile_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='massage_to_gender',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='massage_to_female',
            field=models.BooleanField(blank=True, null=True, verbose_name='жкнщинам'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='massage_to_male',
            field=models.BooleanField(blank=True, null=True, verbose_name='массаж мужчинам'),
        ),
    ]
