# Generated by Django 4.2.2 on 2023-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_therapistprofile_massage_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='is_profile_active',
            field=models.BooleanField(default=False),
        ),
    ]
