# Generated by Django 4.2.2 on 2023-07-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_service_massagetherapistprofile_instagram_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(default='img/offers/default.jpeg', upload_to='img/offers', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='therapist',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Массажист'),
        ),
    ]
