# Generated by Django 4.2.2 on 2023-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_therapistprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='massage_to_female',
            field=models.BooleanField(blank=True, null=True, verbose_name='женщинам'),
        ),
    ]
