# Generated by Django 4.2.2 on 2023-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_therapistprofile_massage_to_female'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
