# Generated by Django 4.2.2 on 2023-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_therapistprofile_latitude_therapistprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='massage_to_female',
            field=models.BooleanField(blank=True, default=True, verbose_name='женщинам'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='massage_to_male',
            field=models.BooleanField(blank=True, default=True, verbose_name='массаж мужчинам'),
        ),
    ]
