# Generated by Django 4.2.2 on 2023-07-13 16:06

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_age_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_crop',
            field=image_cropping.fields.ImageRatioField('avatar', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar crop'),
        ),
    ]
