# Generated by Django 4.2.2 on 2023-07-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_photo_alter_listing_therapist'),
        ('users', '0008_userprofile_avatar_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massagetherapistprofile',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='massagetherapistprofile',
            name='services',
            field=models.ManyToManyField(to='listings.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='massagetherapistprofile',
            name='show_instagram_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='massagetherapistprofile',
            name='show_phone_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='massagetherapistprofile',
            name='show_telegram_profile',
            field=models.BooleanField(default=True),
        ),
    ]
