# Generated by Django 4.2.2 on 2023-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_therapistprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='massage_to_couples',
            field=models.BooleanField(blank=True, default=True, verbose_name='парам'),
        ),
    ]
