# Generated by Django 4.2.2 on 2023-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_contact_number_massagetherapistprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagetherapistprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='massagetherapistprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Возраст'),
        ),
    ]
