# Generated by Django 4.2.2 on 2023-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_rename_basicservices_basicservice'),
        ('users', '0009_therapistprofile_massage_to_couples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='massage_to_couples',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='massage_to_female',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='massage_to_male',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='show_address',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='show_instagram_profile',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='show_phone_number',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='show_telegram_profile',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='basic_services',
            field=models.ManyToManyField(to='listings.basicservice'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='features',
            field=models.ManyToManyField(to='listings.feature'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='massage_for',
            field=models.ManyToManyField(to='listings.massagefor'),
        ),
    ]
