# Generated by Django 4.2.2 on 2023-07-14 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_alter_listing_photo_alter_listing_therapist'),
        ('users', '0010_remove_massagetherapistprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassageTherapistProfile',
            new_name='TherapistProfile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_crop',
        ),
    ]
