# Generated by Django 4.2.2 on 2023-10-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_basicservice_home_price_and_more'),
        ('users', '0010_remove_therapistprofile_massage_to_couples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='basic_services',
            field=models.ManyToManyField(to='listings.basicserviceprice'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='features',
            field=models.ManyToManyField(blank=True, to='listings.feature'),
        ),
    ]
