# Generated by Django 4.2.2 on 2023-10-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_basicservice_home_price_basicservice_on_site_price_and_more'),
        ('users', '0011_alter_therapistprofile_basic_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='basic_services',
            field=models.ManyToManyField(to='listings.basicservice'),
        ),
    ]
