# Generated by Django 4.2.2 on 2023-07-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_massagetherapistprofile_therapistprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
    ]
