# Generated by Django 4.2.2 on 2023-07-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_therapistprofile_show_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
