# Generated by Django 4.2.2 on 2023-10-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_basicservice_home_price_and_more'),
        ('users', '0013_alter_therapistprofile_basic_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='basic_services',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='basic_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.basicserviceprice'),
        ),
    ]
