# Generated by Django 4.2.2 on 2023-10-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_basicserviceprice_specialist'),
        ('users', '0014_remove_therapistprofile_basic_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='basic_services',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='basic_services',
            field=models.ManyToManyField(to='listings.basicservice'),
        ),
    ]
