# Generated by Django 4.2.2 on 2023-10-23 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_basicserviceprice_specialist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_remove_therapistprofile_basic_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='basic_services',
            field=models.ManyToManyField(blank=True, to='listings.basicservice'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', related_query_name='therapist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
